* `searchsorted()` performs binary search in the array and returns the index where the specified value would be inserted to maintain search order
* searchsorted method is assumed to be used on `sorted arrays`

In [2]:
import numpy as np

In [4]:
arr = np.array([3,4,5,6])
index = np.searchsorted(arr,4)
print(index)
index = np.searchsorted(arr,4,side='right')
print(index)

1
2


In [6]:
#not a right way
arr = np.array([4,1,2,0])
index = np.searchsorted(arr,4,side='right')
print(index)

4


In [8]:
arr =np.array([3,5,7,9])
index = np.searchsorted(arr,[2,3,10])
print(index)

index = np.searchsorted(arr,[2,3,10],side='right')
print(index)

# side = 'left' or 'right' comes into picture when there are duplicates


[0 0 4]
[0 1 4]


Sorting Arrays
--------------

In [11]:
arr = np.array([4,1,2,0])
print(np.sort(arr))

arr = np.array([[3,2,5],[6,0,4]])
print(np.sort(arr))

[0 1 2 4]
[[2 3 5]
 [0 4 6]]


Filtering Arrays
----------------

In [16]:
arr = np.arange(1,10)

#filter array
filter_arr = []
for element in arr:
    if element%2==0:
        filter_arr.append(False)
    else:
        filter_arr.append(True)

new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)

[True, False, True, False, True, False, True, False, True]
[1 3 5 7 9]


In [18]:
arr = np.arange(1,10)
filter_arr = arr%2==1
new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)

[ True False  True False  True False  True False  True]
[1 3 5 7 9]
