* `searchsorted()` performs binary search in the array and returns the index where the specified value would be inserted to maintain search order
* searchsorted method is assumed to be used on `sorted arrays`

In [4]:
import numpy as np

In [5]:
arr = np.array([3,4,5,6])
index = np.searchsorted(arr,4)
print(index)
index = np.searchsorted(arr,4,side='right')
print(index)

1
2


In [6]:
#not a right way
arr = np.array([4,1,2,0])
index = np.searchsorted(arr,4,side='right')
print(index)

4


In [7]:
arr =np.array([3,5,7,9])
index = np.searchsorted(arr,[2,3,10])
print(index)

index = np.searchsorted(arr,[2,3,10],side='right')
print(index)

# side = 'left' or 'right' comes into picture when there are duplicates


[0 0 4]
[0 1 4]


Sorting Arrays
--------------

In [8]:
arr = np.array([4,1,2,0])
print(np.sort(arr))

arr = np.array([[3,2,5],[6,0,4]])
print(np.sort(arr))

[0 1 2 4]
[[2 3 5]
 [0 4 6]]


Filtering Arrays
----------------

In [9]:
arr = np.arange(1,10)

#filter array
filter_arr = []
for element in arr:
    if element%2==0:
        filter_arr.append(False)
    else:
        filter_arr.append(True)

new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)

[True, False, True, False, True, False, True, False, True]
[1 3 5 7 9]


In [10]:
arr = np.arange(1,10)
filter_arr = arr%2==1
new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)

[ True False  True False  True False  True False  True]
[1 3 5 7 9]


In [15]:
#create a filter to filter out prime number between 10 to 100
numbers = [*range(10,1001)]
# print(numbers)
arr = np.array(numbers)

def is_prime(number):
    for index in range(2,number//2+1):
        if number%index==0:
            return False
    return True

filter_arr = []
for element in arr:
    if is_prime(element):
        filter_arr.append(True)
    else:
        filter_arr.append(False)
# print(filter_arr)
print(arr[filter_arr])

[ 11  13  17  19  23  29  31  37  41  43  47  53  59  61  67  71  73  79
  83  89  97 101 103 107 109 113 127 131 137 139 149 151 157 163 167 173
 179 181 191 193 197 199 211 223 227 229 233 239 241 251 257 263 269 271
 277 281 283 293 307 311 313 317 331 337 347 349 353 359 367 373 379 383
 389 397 401 409 419 421 431 433 439 443 449 457 461 463 467 479 487 491
 499 503 509 521 523 541 547 557 563 569 571 577 587 593 599 601 607 613
 617 619 631 641 643 647 653 659 661 673 677 683 691 701 709 719 727 733
 739 743 751 757 761 769 773 787 797 809 811 821 823 827 829 839 853 857
 859 863 877 881 883 887 907 911 919 929 937 941 947 953 967 971 977 983
 991 997]


In [19]:
#array from 10 to 1000
arr = np.arange(10,10**3+1)
is_prime_vector = np.vectorize(is_prime)
print(arr[is_prime_vector(arr)])

[ 11  13  17  19  23  29  31  37  41  43  47  53  59  61  67  71  73  79
  83  89  97 101 103 107 109 113 127 131 137 139 149 151 157 163 167 173
 179 181 191 193 197 199 211 223 227 229 233 239 241 251 257 263 269 271
 277 281 283 293 307 311 313 317 331 337 347 349 353 359 367 373 379 383
 389 397 401 409 419 421 431 433 439 443 449 457 461 463 467 479 487 491
 499 503 509 521 523 541 547 557 563 569 571 577 587 593 599 601 607 613
 617 619 631 641 643 647 653 659 661 673 677 683 691 701 709 719 727 733
 739 743 751 757 761 769 773 787 797 809 811 821 823 827 829 839 853 857
 859 863 877 881 883 887 907 911 919 929 937 941 947 953 967 971 977 983
 991 997]


Random Numbers with Numpy
-------------------------

In [26]:
from numpy import random

# random number betweeen 0 to 1000
print(random.randint(1000))

#random float -> 0 to 1
print(random.rand())

#random array
print(random.randint(1000,size=(10)))

#2D array
print(random.randint(1000,size=(3,5)))

array = [850,380,238,272,986,489,726,964,918,218]
print(random.choice(array))
print(random.choice(array,size=(3,3)))

886
0.11461957490376096
[135 167 749 344  90 347 391 998 534 275]
[[ 35   6 888 689 698]
 [577 483 917 763 590]
 [710 629 265 207 896]]
964
[[238 489 964]
 [850 218 380]
 [238 218 964]]


Random Distribution
-------------------
* This is set of random numbers tha tfollow a certain probability density function



In [29]:
# * Generate a 1-D array containing 50 values where each value has to 0,1,2,3or 4
#     * Probability for the value to be 0 is 0.1
#     * Probability for the value to be 3 is 0.2
#     * Probability for the value to be 1 is 0.3
#     * Probability for the value to be 2 is 0.2
#     * Probability for the value to be 4 is 0.2

values = random.choice([0,1,2,3,4],p=[0.1,0.3,0.2,0.2,0.2],size=50)
print(values)

dice_rolls = random.choice([1,2,3,4,5,6],p=[1/6,1/6,1/6,1/6,1/6,1/6],size =100)
print(dice_rolls)

[3 2 2 3 4 1 2 1 4 4 1 0 1 3 2 4 3 2 3 2 0 1 4 1 2 1 4 4 2 2 3 1 1 4 1 1 4
 0 4 3 2 2 4 1 1 1 1 3 2 3]
[4 6 1 1 3 2 3 6 1 2 1 3 1 4 4 4 4 4 4 2 3 4 3 2 4 6 1 5 1 3 6 3 3 5 6 2 4
 2 5 5 4 1 6 1 6 3 3 4 5 2 5 1 6 1 2 2 3 3 6 4 1 1 5 6 2 6 4 5 4 6 6 6 2 2
 3 5 2 2 2 6 2 4 4 1 5 2 3 1 5 1 3 5 3 5 1 3 4 4 3 6]


In [31]:
# * Generate a 2-D array containing 4*5 values where each value has to 0,1,2,3or 4
values = random.choice([0,1,2,3,4],p =[0.1,0.3,0.2,0.2,0.2],size=(4,5))
print(values)

[[3 4 3 1 2]
 [3 1 4 1 4]
 [3 4 3 2 0]
 [1 0 0 3 1]]


Shuffling arrays
----------------
Shuffling makes changes in the original array

In [40]:
arr = np.array(['2','3','4','5','6','7','8','9','10','J','Q','K','A'])
random.shuffle(arr)
print(arr)

arr = np.array(['2','3','4','5','6','7','8','9','10','J','Q','K','A'])
print(random.permutation(arr))
print(arr)
#permutation returns the rearranged array and original array will remain unchanged



['8' 'A' '9' '4' '10' '7' 'J' '3' '5' 'K' '2' '6' 'Q']
['3' 'Q' 'A' '10' '5' '7' '8' 'J' '2' 'K' '9' '4' '6']
['2' '3' '4' '5' '6' '7' '8' '9' '10' 'J' 'Q' 'K' 'A']
