In [3]:
import numpy as np

Reshaping Arrays(contd)

In [6]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11])
newarr = arr.reshape(2,2,-1)
newarr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [7]:
arr = np.array([0,1,2,3,4,5,6,7])
newarr = arr.reshape(2,2,-1)
newarr

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [8]:
# pass -1 as dimension more than once, it will trough error
arr = np.array([0,1,2,3,4,5,6,7])
newarr = arr.reshape(2,-1,-1)
newarr

ValueError: can only specify one unknown dimension

In [9]:
arr = np.array([0,1,2,3,4,5,6,7])
newarr = arr.reshape(2,-1,2)
newarr

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(2,3,1)
newarr

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [10]:
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
newarr

array([1, 2, 3, 4, 5, 6])

flatten arrays

In [17]:
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(newarr)
arr = np.array([0,1,2,3,4,5,6,7])
newarr=arr.reshape(-1,2,2)
print(newarr)
flatten_array = newarr.reshape(-1)
print(flatten_array)

[1 2 3 4 5 6]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[0 1 2 3 4 5 6 7]


In [19]:
arr = np.arange(10)
for item in arr:
    print(item)

0
1
2
3
4
5
6
7
8
9


In [21]:
arr =np.array([[0,1,2,3],[4,5,6,7]])
for item in arr:
    print(item)

#it is 2D array so double loop 
for x_item in arr:
    for y_item in x_item:
        print(y_item)

[0 1 2 3]
[4 5 6 7]
0
1
2
3
4
5
6
7


In [23]:
arr =np.

arr

TypeError: Cannot interpret '1' as a data type

Itertaing using nditer

In [25]:
arr =np.array([[[0,1],[2,3],[4,5],[6,7]]])

for item in np.nditer(arr):
    print(item)

0
1
2
3
4
5
6
7


Iterating array with dtype

In [30]:
arr =np.array([[[0,1],[2,3],[4,5],[6,7]]])
print(f"convert into String")
for item in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(item)
print('\n')
print(f"convert into Float")
for item in np.nditer(arr,flags=['buffered'],op_dtypes=['f'],casting='unsafe'):
    print(item)

convert into String
b'0'
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'


convert into Float
0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0


In [32]:
arr=np.array([[0,1,2,3],[4,5,6,7]])

for item in np.nditer(arr[:, ::2]):
    print(item)

0
2
4
6


In [34]:
arr=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
print('Step of 2 in second dimension')
for item in np.nditer(arr[:, ::2]):
    print(item)
print('\n')
print("step of 2 in 1st dimension")
for item in np.nditer(arr[::2, :]):
    print(item)

Step of 2 in second dimension
0
2
4
6
8
10
12
14


step of 2 in 1st dimension
0
1
2
3
8
9
10
11


Joining arrays with numpy
-------------------------

In [35]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])
arr = np.concatenate((arr_1,arr_2))
arr

array([1, 2, 3, 4, 5, 6])

In [38]:
arr_1 =np.array([[1,2],[3,4]])
arr_2 =np.array([[5,6],[7,8]])
arr = np.concatenate((arr_1,arr_2))
print(arr)
print(f" concatenate with axis =1")
arr = np.concatenate((arr_1,arr_2),axis=1)
print(arr)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
 concatenate with axis =1
[[1 2 5 6]
 [3 4 7 8]]


In [49]:
#we can increase the axis as the dimension increases
arr_1 =np.array([1,2,3])
arr_2 =np.array([4,5,6])
arr = np.stack((arr_1,arr_2),axis=1)
print(f" stack with axis =1")
print(arr)
print(f" stack with axis =2")
arr = np.stack((arr_1,arr_2),axis=0)
print(arr)
arr_1 =np.array([[1,2],[3,4]])
arr_2 =np.array([[5,6],[7,8]])
arr = np.stack((arr_1,arr_2),axis=1)
print(f" stack with axis =1")
print(arr)
print(f" stack with axis =2")
arr = np.stack((arr_1,arr_2),axis=0)
print(arr)


 stack with axis =1
[[1 4]
 [2 5]
 [3 6]]
 stack with axis =2
[[1 2 3]
 [4 5 6]]
 stack with axis =1
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
 stack with axis =2
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [53]:
# Stacking along rows
arr_1 =np.array([1,2,3])
arr_2 =np.array([4,5,6])
arr = np.hstack((arr_1,arr_2))
print(f"Row Stacking")
print(arr)

print('\n')
# Stacking along columns
arr = np.vstack((arr_1,arr_2))
print(f"Column Stacking")
print(arr)

print('\n')
# Stacking along columns
arr = np.dstack((arr_1,arr_2))
print(f"Height Stacking")
print(arr)

Row Stacking
[1 2 3 4 5 6]


Column Stacking
[[1 2 3]
 [4 5 6]]


Height Stacking
[[[1 4]
  [2 5]
  [3 6]]]


Searching arrays

In [56]:
arr = np.array([0,1,2,3,4,5,6,7])
item = np.where(arr==2)
print(item)

items = np.where(arr%2==0)
print(items)

items = np.where(arr>5)
print(items)

(array([2], dtype=int64),)
(array([0, 2, 4, 6], dtype=int64),)
(array([6, 7], dtype=int64),)


In [62]:
arr = np.array([0,1,2,3,4,5,6,7])

index = np.searchsorted(arr,5)
print(index)

arr = np.array([15,3,4,1,9,10,6,5])
index = np.searchsorted(arr,5)
print(index)
index = np.searchsorted(arr,5,side='right')
print(index)

5
4
4
