Universal functions (Ufuncs)
---------------------------
* ufuncs are numpy functions that operates on ndarray object
* They are used to implement vectorization in Numpy Which is faster than iterating over elements
* ufuncs take additional args
    * where
    * dtype
    * out

In [3]:
import numpy as np

In [4]:
#Traditional python approach
x = [1,3,5,7]
y = [2,4,6,8]
z = []

for i,j in zip(x,y):
    z.append(i+j)
print(z)

#ufunc approach
z = np.add(x,y)
print(z)

[3, 7, 11, 15]
[ 3  7 11 15]


Creating oun functions
----------------------
* To create own functions, we need to define a function just like normal functions in python and add it to the Numpy ufnc library from the `frompyfun()` method.
* This `frompyfunc()` method takes the following arguments
    * function -  name of the function
    * the number of input arguments (arrays)
    * The number of Output arguments

In [6]:
def my_add(x,y):
    return x+y

def my_sub(x,y):
    return x-y

my_add = np.frompyfunc(my_add,2,1)
my_sub = np.frompyfunc(my_sub,2,1)

print(f"Result of add = {my_add([1,2,3,4,5],[6,7,8,9,10])}")
print(f"Result of sub = {my_sub([1,2,3,4,5],[6,7,8,9,10])}")

Result of add = [7 9 11 13 15]
Result of sub = [-5 -5 -5 -5 -5]


In [7]:
print(type(my_add))
print(type(my_sub))

<class 'numpy.ufunc'>
<class 'numpy.ufunc'>


Arithmatic Ufuncs
-----------------

In [10]:
arr1 = np.array([10,20,30])
arr2 = np.array([2,4,6])

print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))
print(np.power(arr1,arr2))
print(np.mod(arr1,arr2))

[12 24 36]
[ 8 16 24]
[ 20  80 180]
[5. 5. 5.]
[      100    160000 729000000]
[0 0 0]


Decimal rounding Ufuncs:
------------------------
* Truncation
* fix
* floor
* rounding
* floor
* cell

In [13]:
print(np.trunc([-33.33333333333333333,33.3333333333333333]))
print(np.fix([-33.33333333333333333,33.3333333333333333]))
print(np.floor([-33.33333333333333333,33.3333333333333333]))
print(np.ceil([-33.33333333333333333,33.3333333333333333]))
print(np.round(33.33333333333333333,2))


[-33.  33.]
[-33.  33.]
[-34.  33.]
[-33.  34.]
33.33


Logarithms
----------

In [16]:
#Log at base2
arr = np.arange(1,10)
print(np.log2(arr))

#Log at base10
print(np.log10(arr))

#Log at base e
print(np.log(arr))


from math import log
nplog = np.frompyfunc(log,2,1)
print(nplog(100,15))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
1.7005483074552052


LCM and HCF/GCD
---------------

In [26]:
print(np.lcm(4,6))
arr = np.array([3,6,9])
print(np.lcm.reduce(arr))
arr = np.arange(2,20)
print(np.lcm.reduce(arr))

12
18
232792560


In [27]:
print(np.gcd(6,12))
arr = np.array([3,6,9])
print(np.gcd.reduce(arr))
arr = np.arange(2,20)
print(np.gcd.reduce(arr))


6
3
1


Trignometric functions
----------------------

In [29]:
print(np.sin(np.pi/2))

arr = np.array([0,30,45,60,90,120,180,270,360])

#convert degree into radians
radians = np.deg2rad(arr)
print(radians)

1.0
[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265 4.71238898 6.28318531]


Set Operations
--------------

In [31]:
arr = np.arange(1,9)
unique_arr = np.unique(arr)
print(unique_arr)

arr1 = np.array([10,20,30,40,50])
arr2 = np.array([40,50,60,70,80])

print(np.union1d(arr1,arr2))
print(np.intersect1d(arr1,arr2))
print(np.setdiff1d(arr1,arr2))
print(np.setxor1d(arr1,arr2))

[1 2 3 4 5 6 7 8]
[10 20 30 40 50 60 70 80]
[40 50]
[10 20 30]
[10 20 30 60 70 80]
