Numpy
-----

In [1]:
import numpy as np

In [3]:
my_list = [1,'a',True]
print(my_list)
print(type(my_list))

[1, 'a', True]
<class 'list'>


* The array object in numpy is calledd ndarray
* In Numpy array all the objects items are of sametype, so no need to store meta data,so it is faster than lists

In [4]:
array_1 = np.array([1,2,3])
print(array_1)
print(type(array_1))

[1 2 3]
<class 'numpy.ndarray'>


* The type of array is numpy.ndarray which refers to ndimensional array
* ndarray can be created from lists or tuples

In [5]:
array_2 = np.array((1,2,3))
print(array_2)
print(type(array_2))

[1 2 3]
<class 'numpy.ndarray'>


In [13]:
def print_array_n_dimension(array):
    print(array)
    print(f"type {type(array)}")
    print(f"Dimension is {array.ndim}")

In [16]:
a = np.array(12)
print_array_n_dimension(a)
b = np.array([1,2,3])
print_array_n_dimension(b)
c =np.array([[1,2,3],[4,5,6]])
print_array_n_dimension(c)
d = np.array([[[1,2,3],[4,5,6]],[[-1,-2,-3],[-4,-5,-6]]])
print_array_n_dimension(d)
e = np.array([[1,2,3,7],[4,5,6,8],[-1,-2,-3,-7],[-4,-5,-6,-8]])
print_array_n_dimension(e)


12
type <class 'numpy.ndarray'>
Dimension is 0
[1 2 3]
type <class 'numpy.ndarray'>
Dimension is 1
[[1 2 3]
 [4 5 6]]
type <class 'numpy.ndarray'>
Dimension is 2
[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]
type <class 'numpy.ndarray'>
Dimension is 3
[[ 1  2  3  7]
 [ 4  5  6  8]
 [-1 -2 -3 -7]
 [-4 -5 -6 -8]]
type <class 'numpy.ndarray'>
Dimension is 2


In [25]:
#zero dimension
print(a)
#one dimension
print(b[0])
#two dimension
print(f"c[0]= {c[0]}")
print(f"c[0,1]= {c[0,1]}")
print(f"c[0,0]= {c[0,0]}")
#three dimension
print(f"d[0]= {d[0]}")
print(f"d[0,1]= {d[0,1]}")
print(f"d[0,1,1]= {d[0,1,1]}")


12
1
c[0]= [1 2 3]
c[0,1]= 2
c[0,0]= 1
d[0]= [[1 2 3]
 [4 5 6]]
d[0,1]= [4 5 6]
d[0,1,1]= 5


In [26]:
my_list = [1,2,3,4]
print(f"my_list[0], {my_list[0]}")
print(f"my_list[3], {my_list[3]}")
print(f"my_list[-1], {my_list[-1]}")

my_list[0], 1
my_list[3], 4
my_list[-1], 4


In [28]:
#neagtive indexing
print(c)
print(f"c[-1,0] = {c[-1,0]}")

[[1 2 3]
 [4 5 6]]
c[-1,0] = 4


In [36]:
my_list = [1,2,3,4,5,6,7,8,9,10]
print(my_list)
print(my_list[0:3])
print(my_list[0:6:2])
print(my_list[4:])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3]
[1, 3, 5]
[5, 6, 7, 8, 9, 10]


In [37]:
arr = np.arange(1,11)
print(arr)
print(arr[0:3])
print(arr[0:6:2])
print(arr[4:])

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3]
[1 3 5]
[ 5  6  7  8  9 10]


In [42]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr[-1,0:2])
print(arr[0:2,1:4])
#0:2 selecting 1st and 2nd arrays and 1:4 slicing those arrays

[11 12]
[[2 3 4]
 [7 8 9]]


Data Types
----------

* `i` : integer
* `b` : boolean
* `u` : unsigned integer
* `f` : float
* `c` : complex float
* `m` : timedelta
* `M` : datetime
* `O` : object
* `S` : string
* `U` : unicode string

In [48]:
print(arr)
print(arr.dtype)
arr = np.array(['dell','hp','lenovo'])
print(arr)
print(arr.dtype)
arr = np.array(['dell','hp','lenovo'],dtype='S')
print(arr)
print(arr.dtype)
arr = np.array([0,1],dtype='S')
print(arr)
print(arr.dtype)

[b'dell' b'hp' b'lenovo']
|S6
['dell' 'hp' 'lenovo']
<U6
[b'dell' b'hp' b'lenovo']
|S6
[b'0' b'1']
|S1


In [55]:
arr = np.array([2.5,3.6,4.0,5.8])
print(arr)
print(arr.dtype)
new_arr = arr.astype(int)
print(new_arr)
print(new_arr.dtype)
new_arr = arr.astype(str)
print(new_arr)
print(new_arr.dtype)

[2.5 3.6 4.  5.8]
float64
[2 3 4 5]
int32
['2.5' '3.6' '4.0' '5.8']
<U32


In [67]:
arr = np.array([1,2,3,4,5,6,7])
copy_arr = arr.copy()
arr[0] =0
print(f"arr = {arr}")
print(f"copy_arr = {copy_arr}")
print(f"copy_arr is {copy_arr.base}")

arr = [0 2 3 4 5 6 7]
copy_arr = [1 2 3 4 5 6 7]
copy_arr is None


In [71]:
arr = np.array([1,2,3,4,5,6,7])
view_arr = arr.view()
print('before change')
print(f"arr = {arr}")
print(f"view_arr = {view_arr}")
print(f"copy_arr is {view_arr.base} \n")

arr[0] = 0
print('after 1st change')
print(f"arr = {arr}")
print(f"view_arr = {view_arr}")
print(f"copy_arr is {view_arr.base}\n")

view_arr[-1] = 8
print('after 2nd change')
print(f"arr = {arr}")
print(f"view_arr = {view_arr}")
print(f"copy_arr is {view_arr.base}")

#view does not make any change, its just different name for the same location

before change
arr = [1 2 3 4 5 6 7]
view_arr = [1 2 3 4 5 6 7]
copy_arr is [1 2 3 4 5 6 7] 

after 1st change
arr = [0 2 3 4 5 6 7]
view_arr = [0 2 3 4 5 6 7]
copy_arr is [0 2 3 4 5 6 7]

after 2nd change
arr = [0 2 3 4 5 6 8]
view_arr = [0 2 3 4 5 6 8]
copy_arr is [0 2 3 4 5 6 8]


Shape of Array : The shape of array is number of elements in each dimension

In [79]:
arr = np.array([1,2,3,4,5,6,7])
print(f"shape of {arr} is {arr.shape}\n")

arr = np.array([[1,2,3,4],[5,6,7,8]])
print(f"shape of {arr} is {arr.shape}\n")
# arr.shape (2,4) where 2 means 1st dimension has 2 elements and 2nd dimension has 4 elements

arr = np.array([1,2,3],ndmin=3)
print(f"shape of {arr} is {arr.shape}\n")
# arr.shape (1,1,3) where 2 means 1st dimension has 1 element, 2nd dimension has 1 element and 3rd dimension has 3 elements
# since arrays does not support multi dimension in each dimension they will have same number of elements


shape of [1 2 3 4 5 6 7] is (7,)

shape of [[1 2 3 4]
 [5 6 7 8]] is (2, 4)

shape of [[[1 2 3]]] is (1, 1, 3)



In [82]:
#Reshape from 1D to 2D
arr = np.array([0,1,2,3,4,5,6,7,8])
new_arr = arr.reshape(3,3)
print(new_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [84]:
#Reshape from 1D to 2D
arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11])
new_arr = arr.reshape(2,3,2)
print(new_arr)
print(new_arr.base)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
