In [2]:
import numpy as np

$$f(x) = x^2 + e^x +\frac{2}{3\sqrt{x}}$$

In [8]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [9]:
type(a)

numpy.ndarray

Indexing elements in my numpy array

In [11]:
a=np.array([10,20,30,40,50])
a[0:2]

array([10, 20])

In [8]:
A = np.array([[1,2,3,4],[10,20,30,40],[100,200,300,400],[1000,2000,3000,4000]])

In [28]:
A

array([[   1,    2,    3,    4],
       [  10,   20,   30,   40],
       [ 100,  200,  300,  400],
       [1000, 2000, 3000, 4000]])

In [29]:
A.shape

(4, 4)

In [30]:
A.shape[0]

4

In [31]:
A.shape[1]

4

In [32]:
A[2,3]

400

Extracting a Submatrix

In [34]:
A[1:3]

array([[ 10,  20,  30,  40],
       [100, 200, 300, 400]])

In [37]:
A[:,1:4]

array([[   2,    3,    4],
       [  20,   30,   40],
       [ 200,  300,  400],
       [2000, 3000, 4000]])

In [39]:
B = A[1:3,1:4]
B

array([[ 20,  30,  40],
       [200, 300, 400]])

Modify elements in Matrix or array

In [40]:
A[2,1] =1/3

In [41]:
A

array([[   1,    2,    3,    4],
       [  10,   20,   30,   40],
       [ 100,    0,  300,  400],
       [1000, 2000, 3000, 4000]])

ifyou are working with float, then convert matrix into float before operating on it. even if we give one value in float then whole matrix converts into float

In [44]:
A = np.array([[1.0,2,3,4],[10,20,30,40],[100,200,300,400],[1000,2000,3000,4000]])
A

array([[1.e+00, 2.e+00, 3.e+00, 4.e+00],
       [1.e+01, 2.e+01, 3.e+01, 4.e+01],
       [1.e+02, 2.e+02, 3.e+02, 4.e+02],
       [1.e+03, 2.e+03, 3.e+03, 4.e+03]])

In [45]:
A[2,1] =1/3

In [7]:
A


NameError: name 'A' is not defined

Creating Speacial matrices

In [47]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [50]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
k=np.identity(10)

In [52]:
k

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [53]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [54]:
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [55]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [56]:
np.ones((6,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
10*np.ones((4,4))

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

np.full((),10) is better than 10*np.ones as former performs less operations to give same output

In [59]:
np.full((4,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [58]:
np.full(k.shape,1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [66]:
x= np.random.random((2,2))
x

array([[0.58325615, 0.04780096],
       [0.03573448, 0.02232956]])

In [67]:
x= np.random.random()
x

0.6135996431111119

In [3]:
x=np.random.random((1000,1))
x


array([[9.91508469e-01],
       [7.69091674e-01],
       [6.90633753e-01],
       [3.79648400e-01],
       [6.75304242e-01],
       [4.47855948e-01],
       [6.59733583e-02],
       [9.10968869e-02],
       [3.26435191e-01],
       [4.11700158e-01],
       [4.03194348e-01],
       [6.90388156e-02],
       [8.69412829e-01],
       [6.75771390e-01],
       [4.51885101e-01],
       [2.56296351e-01],
       [5.31422526e-01],
       [6.02539959e-01],
       [5.46169609e-01],
       [7.19256223e-01],
       [8.14244258e-01],
       [5.51039444e-01],
       [6.27050141e-01],
       [5.13338822e-01],
       [9.51424047e-01],
       [5.55843886e-01],
       [2.09480567e-01],
       [3.68408728e-02],
       [1.89776097e-01],
       [6.34175943e-01],
       [3.63076798e-01],
       [4.86745889e-01],
       [5.35305353e-02],
       [8.88862333e-01],
       [3.09261120e-01],
       [8.20017556e-01],
       [3.25987775e-01],
       [8.30773715e-01],
       [3.89731036e-01],
       [8.22570187e-01],


In [4]:
np.mean(x)

0.5001121345848402

$$Var(x) = E(x^2) - E^2(x) = \int_{0}^1 x^2 \ dx-\frac{1}{4} = \frac{1}{3} - \frac{1}{4} = \frac{1}{12}

In [5]:
np.std(x)**2

0.08684964984747992

as type() function in python dont give the type of characters in the array, returns numpy.ndarray, to find the type of data in array we use dtype

In [ ]:
A = np.array([[1,2,3,4],[10,20,30,40],[100,200,300,400],[1000,2000,3000,4000]])

In [10]:
A.dtype

dtype('int32')

In [11]:
A = np.array([[1.0,2,3,4],[10,20,30,40],[100,200,300,400],[1000,2000,3000,4000]])

In [12]:
A.dtype

dtype('float64')