In [1]:
import numpy as np

MATRIX ADDITION

In [2]:
A = np.array([[1,5,6],[1,8,9],[0,-1,6]])
B = np.array([[4,8,4],[1,0,5],[6,-8,4]])

In [3]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [4]:
B

array([[ 4,  8,  4],
       [ 1,  0,  5],
       [ 6, -8,  4]])

In [5]:
A+B

array([[ 5, 13, 10],
       [ 2,  8, 14],
       [ 6, -9, 10]])

In [6]:
C=A+B
C

array([[ 5, 13, 10],
       [ 2,  8, 14],
       [ 6, -9, 10]])

In [7]:
np.add(A,B)

array([[ 5, 13, 10],
       [ 2,  8, 14],
       [ 6, -9, 10]])

if we want different dtype, we can use np.add

In [8]:
np.add(A,B, dtype = np.float64)

array([[ 5., 13., 10.],
       [ 2.,  8., 14.],
       [ 6., -9., 10.]])

MATRIX SUBTRACTION

In [9]:
C=A-B
C

array([[-3, -3,  2],
       [ 0,  8,  4],
       [-6,  7,  2]])

In [10]:
np.subtract(A,B, dtype=np.float64)

array([[-3., -3.,  2.],
       [ 0.,  8.,  4.],
       [-6.,  7.,  2.]])

Matrix Multiplication

Pointwise Multiplication

In [11]:
C=A*B
C

array([[ 4, 40, 24],
       [ 1,  0, 45],
       [ 0,  8, 24]])

In [12]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [13]:
B

array([[ 4,  8,  4],
       [ 1,  0,  5],
       [ 6, -8,  4]])

In [14]:
C=np.multiply(A,B, dtype = np.float64)
C

array([[ 4., 40., 24.],
       [ 1.,  0., 45.],
       [ 0.,  8., 24.]])

MATRIX DIVISION(Pointwise)

In [15]:
C=A/B

C:\Users\vamsh\AppData\Local\Temp/ipykernel_1324/4126679657.py:1: RuntimeWarning: divide by zero encountered in true_divide
  C=A/B


In [16]:
C

array([[0.25 , 0.625, 1.5  ],
       [1.   ,   inf, 1.8  ],
       [0.   , 0.125, 1.5  ]])

In [17]:
C=np.divide(A,B, dtype = np.float64)

C:\Users\vamsh\AppData\Local\Temp/ipykernel_1324/3750612579.py:1: RuntimeWarning: divide by zero encountered in true_divide
  C=np.divide(A,B, dtype = np.float64)


In [18]:
C

array([[0.25 , 0.625, 1.5  ],
       [1.   ,   inf, 1.8  ],
       [0.   , 0.125, 1.5  ]])

In [19]:
np.int16(C)

array([[0, 0, 1],
       [1, 0, 1],
       [0, 0, 1]], dtype=int16)

#MATRIX PRODUCTS

In [20]:
np.matmul(A,B)

array([[ 45, -40,  53],
       [ 66, -64,  80],
       [ 35, -48,  19]])

$$ C = AB $$

$$C_{ij} = \sum_{k=1}^N A_{ik} B_{kj}

In [21]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [22]:
B

array([[ 4,  8,  4],
       [ 1,  0,  5],
       [ 6, -8,  4]])

In [23]:
 R= np.array([[1,2,3,4],[2,5,6,8],[1,2,4,10]])
 R

array([[ 1,  2,  3,  4],
       [ 2,  5,  6,  8],
       [ 1,  2,  4, 10]])

In [24]:
np.matmul(A,R)

array([[ 17,  39,  57, 104],
       [ 26,  60,  87, 158],
       [  4,   7,  18,  52]])

In [25]:
np.matmul(R,A)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [ ]:
np.matmul(R.transpose(),A)

array([[  3,  20,  30],
       [  7,  48,  69],
       [  9,  59,  96],
       [ 12,  74, 156]])

In [ ]:
a=A[:,0]
a

array([1, 1, 0])

In [ ]:
b=B[:,0]
b

array([4, 1, 6])

In [ ]:
c = a*b
c

array([4, 1, 0])

In [26]:
np.matmul(a,b)

NameError: name 'a' is not defined

In [ ]:
np.dot(a,b)

5

In [27]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [28]:
B

array([[ 4,  8,  4],
       [ 1,  0,  5],
       [ 6, -8,  4]])

In [29]:
np.dot(A,B)

array([[ 45, -40,  53],
       [ 66, -64,  80],
       [ 35, -48,  19]])

In [30]:
np.matmul(A,B)

array([[ 45, -40,  53],
       [ 66, -64,  80],
       [ 35, -48,  19]])

$$ <a,b> = a^Tb = \sum_{i=1}^n a_i b_i$$

In [31]:
np.inner(a,b)

NameError: name 'a' is not defined

In [32]:
C=  np.tensordot(A,B)
C

array(146)

In [33]:
C = np.tensordot(a,b)
C

NameError: name 'a' is not defined

In [39]:
a = np.arange(60.).reshape(3,4,5)
b= np.arange(24.).reshape(4,3,2)
a


array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]],

       [[20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34.],
        [35., 36., 37., 38., 39.]],

       [[40., 41., 42., 43., 44.],
        [45., 46., 47., 48., 49.],
        [50., 51., 52., 53., 54.],
        [55., 56., 57., 58., 59.]]])

In [40]:
b

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.]],

       [[ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]],

       [[12., 13.],
        [14., 15.],
        [16., 17.]],

       [[18., 19.],
        [20., 21.],
        [22., 23.]]])

In [43]:
np.tensordot(a, b)

ValueError: shape-mismatch for sum

In [44]:
np.tensordot(a, b, axes=([1,0],[0,1]))

array([[4400., 4730.],
       [4532., 4874.],
       [4664., 5018.],
       [4796., 5162.],
       [4928., 5306.]])

In [45]:
np.linalg.matrix_power(A,1)

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [46]:
np.linalg.matrix_power(A,2)

array([[  6,  39,  87],
       [  9,  60, 132],
       [ -1, -14,  27]])

In [47]:
np.matmul(A,A)

array([[  6,  39,  87],
       [  9,  60, 132],
       [ -1, -14,  27]])

Kronecker Product $$ C = A \otimes B$$

In [50]:
C = np.kron(A,B)
C

array([[  4,   8,   4,  20,  40,  20,  24,  48,  24],
       [  1,   0,   5,   5,   0,  25,   6,   0,  30],
       [  6,  -8,   4,  30, -40,  20,  36, -48,  24],
       [  4,   8,   4,  32,  64,  32,  36,  72,  36],
       [  1,   0,   5,   8,   0,  40,   9,   0,  45],
       [  6,  -8,   4,  48, -64,  32,  54, -72,  36],
       [  0,   0,   0,  -4,  -8,  -4,  24,  48,  24],
       [  0,   0,   0,  -1,   0,  -5,   6,   0,  30],
       [  0,   0,   0,  -6,   8,  -4,  36, -48,  24]])

Matrix Decompositions

Cholesky Decomposition:   $$ A = UU^H$$

In [51]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [52]:
U = np.linalg.cholesky(A)
U

array([[ 1.        ,  0.        ,  0.        ],
       [ 1.        ,  2.64575131,  0.        ],
       [ 0.        , -0.37796447,  2.42015348]])

In [53]:
np.matmul(U, U.transpose())

array([[ 1.,  1.,  0.],
       [ 1.,  8., -1.],
       [ 0., -1.,  6.]])

we dont get back exact A , so we use Conjugate function

In [54]:
np.matmul(U, U.transpose().conj())

array([[ 1.,  1.,  0.],
       [ 1.,  8., -1.],
       [ 0., -1.,  6.]])

In [55]:
D = np.array([[1,-2j],[2j,5]])
D

array([[ 1.+0.j, -0.-2.j],
       [ 0.+2.j,  5.+0.j]])

In [56]:
U = np.linalg.cholesky(D)

In [57]:
np.matmul(U, U.transpose().conj())

array([[1.+0.j, 0.-2.j],
       [0.+2.j, 5.+0.j]])

In [58]:
np.matmul(U, U.T.conj())

array([[1.+0.j, 0.-2.j],
       [0.+2.j, 5.+0.j]])

Transpose can also be called using higher case T

In [60]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [61]:
A.T

array([[ 1,  1,  0],
       [ 5,  8, -1],
       [ 6,  9,  6]])

QR Decomposition $$ A = QR $$ np.linalg.qr would result in two matrices, first matrix is Q and Second one is R

In [62]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [63]:
np.linalg.qr(A)

(array([[-0.70710678,  0.63960215, -0.30151134],
        [-0.70710678, -0.63960215,  0.30151134],
        [-0.        ,  0.42640143,  0.90453403]]),
 array([[ -1.41421356,  -9.19238816, -10.60660172],
        [  0.        ,  -2.34520788,   0.63960215],
        [  0.        ,   0.        ,   6.33173824]]))

In [66]:
Q = np.linalg.qr(A)[0]

In [67]:
R = np.linalg.qr(A)[1]

In [68]:
np.matmul(Q,R)

array([[ 1.,  5.,  6.],
       [ 1.,  8.,  9.],
       [ 0., -1.,  6.]])

Eigen Value Decomposition $$A  = PDP^{-1} $$
P = Eigen Vector
D =Diagonal matrix
In resultant first array is Diagnal matrix and second one is P

In [71]:
np.linalg.eig(A)

(array([0.34454138+0.j        , 7.32772931+2.69350537j,
        7.32772931-2.69350537j]),
 array([[ 0.9940235 +0.j        ,  0.52656174+0.00429702j,
          0.52656174-0.00429702j],
        [-0.10749871+0.j        ,  0.80658014+0.j        ,
          0.80658014-0.j        ],
        [-0.01900796+0.j        , -0.11875577+0.24091455j,
         -0.11875577-0.24091455j]]))

In [72]:
(d,p) = np.linalg.eig(A)

In [73]:
d

array([0.34454138+0.j        , 7.32772931+2.69350537j,
       7.32772931-2.69350537j])

In [74]:
p

array([[ 0.9940235 +0.j        ,  0.52656174+0.00429702j,
         0.52656174-0.00429702j],
       [-0.10749871+0.j        ,  0.80658014+0.j        ,
         0.80658014-0.j        ],
       [-0.01900796+0.j        , -0.11875577+0.24091455j,
        -0.11875577-0.24091455j]])

d is a matrix not a vector, so need to convert into diagnal matrix

In [77]:
D = np.diag(d)
D

array([[0.34454138+0.j        , 0.        +0.j        ,
        0.        +0.j        ],
       [0.        +0.j        , 7.32772931+2.69350537j,
        0.        +0.j        ],
       [0.        +0.j        , 0.        +0.j        ,
        7.32772931-2.69350537j]])

$$A = PDP^{-1}$$

In [79]:
np.matmul(np.matmul(p,D),np.linalg.inv(p))

array([[ 1.00000000e+00-1.09325372e-16j,  5.00000000e+00-5.79227293e-17j,
         6.00000000e+00-4.16828246e-16j],
       [ 1.00000000e+00-1.07976587e-16j,  8.00000000e+00+1.37152619e-16j,
         9.00000000e+00-5.60099508e-16j],
       [-5.55111512e-17-2.47087253e-17j, -1.00000000e+00-4.42015838e-18j,
         6.00000000e+00+5.98072232e-17j]])

In [80]:
np.real(np.matmul(np.matmul(p,D),np.linalg.inv(p)))

array([[ 1.00000000e+00,  5.00000000e+00,  6.00000000e+00],
       [ 1.00000000e+00,  8.00000000e+00,  9.00000000e+00],
       [-5.55111512e-17, -1.00000000e+00,  6.00000000e+00]])

In [81]:
np.linalg.eigvals(A)

array([0.34454138+0.j        , 7.32772931+2.69350537j,
       7.32772931-2.69350537j])

Singular Valued Decomposition(SVD) $$A = U S V^T$$

In [82]:
np.linalg.svd(A)

(array([[ 0.52419682, -0.12063215,  0.84300983],
        [ 0.80286468, -0.26006138, -0.53644792],
        [ 0.28394717,  0.95802712, -0.03947205]]),
 array([14.9764806 ,  4.53978289,  0.30886909]),
 array([[ 0.0886097 ,  0.58491408,  0.80624056],
        [-0.08385721, -0.80217028,  0.59117747],
        [ 0.99253025, -0.11999315, -0.02203081]]))

In [83]:
(U, S, V) = np.linalg.svd(A)